// Code generated by Slice Machine. DO NOT EDIT.

import { defineSliceZoneComponents } from "@prismicio/vue";
import { defineAsyncComponent } from "vue";

export const components = defineSliceZoneComponents({
  alternate_grid: defineAsyncComponent(
    () => import("./AlternateGrid/index.vue")
  ),
  call_to_action: defineAsyncComponent(
    () => import("./CallToAction/index.vue")
  ),
  contact_form: defineAsyncComponent(() => import("./ContactForm/index.vue")),
  customer_logos: defineAsyncComponent(
    () => import("./CustomerLogos/index.vue")
  ),
  google_reviews: defineAsyncComponent(
    () => import("./GoogleReviews/index.vue")
  ),
  heading: defineAsyncComponent(() => import("./Heading/index.vue")),
  hero: defineAsyncComponent(() => import("./Hero/index.vue")),
  menu_item: defineAsyncComponent(() => import("./MenuItem/index.vue")),
  navigation_item: defineAsyncComponent(
    () => import("./NavigationItem/index.vue")
  ),
  newsletter: defineAsyncComponent(() => import("./Newsletter/index.vue")),
  portfolio_category: defineAsyncComponent(
    () => import("./PortfolioCategory/index.vue")
  ),
  sub_menu_item: defineAsyncComponent(() => import("./SubMenuItem/index.vue")),
});
